### ISSUE TITLE
Can´t change the driver using Zadig

### ISSUE THREAD

**Issue by twanjaarsveld** [bauermaximilian/LG-360-VR-for-PC#3]
The only device found is a Bluetooth modem 
The LG VR is listed in device manager named "toshiba uh2d"

**Comment by bauermaximilian** [comment]
The Bluetooth modem you're seeing is probably unrelated to the LG VR headset, it's just another USB device pIugged into your PC. Unfortunately, you didn't really provide any more details that could help identifying the issue - so I can only speculate that, maybe, your USB-C port is incompatible with the device, the LG-VR glasses have an unsupported firmware or don't work in general, or there are issues with existing drivers or the Zadig setup. As I didn't write Zadig and am not involved in its development, I can't really help you with troubleshooting - but maybe the people over at the Zadig repository can help, or you'll find something helpful in their [wiki](https://github.com/pbatard/libwdi/wiki/Zadig). As this issue doesn't seem to be related to the LGVRActivator, which this repository is about, I'm closing this issue - but good luck with resolving your problem!

**Comment by twanjaarsveld** [comment]
Thanks for the quick reply I'm trying this in a Surface Go that supports Pnp and the LG-VR is seen as a monitor. You mentioned wrong firmware. I have a brand new headset so is it possible it's the wrong (old) firmware that is the problem?

________________________________

**Comment by bauermaximilian** [comment]
You're welcome! And well, I ordered the headset when it was on discount for 30€ about 4 years ago, so I don't think an outdated firmware could be the problem. I tried the headset when I received it on the following devices with different outcomes: 
- The integrated front USB-C port of my old computer: Only the USB device (for Zadig) got recognized, not the monitor
- The USB-C port on my (Windows-based) Samsung Galaxy Book 12: Either the device didn't get recognized at all, only the USB device got recognized, and (in 10% of the attempts) both the USB device and the monitor got recognized
- A USB-C port with DisplayPort support on a dedicated PCI card: Both the USB device and the monitor got recognized

You could try plugging it into a different PC and see if it shows up there. But as discouraging as this might sound, if you want to have an enjoyable VR experience that just works, I don't think that this LG-VR will make you happy and your invested time will pay off. For me, it was fun getting it to work - but ultimately, even I ended up buying an Oculus Quest 2.

**Comment by twanjaarsveld** [comment]
Thank you so much for the time to reply, yeah thought it might be cool just to play around with, just got one for 14,- eu new in the box including shipping. so I thought why not, it's a nice little device that would have been perfect for use with my small surface go, but yeah if it's a pain to set it up it's probably not worth it, might just try and fix mine old G5 to play around with it.

Thanks again it's really great that people like you take the time to share fun little projects like this

________________________________
